export const countryCodes = [
  { code: "+971", label: "UAE (الإمارات)" },
  { code: "+1", label: "USA/Canada" },
  { code: "+44", label: "UK (بريطانيا)" },
  { code: "+91", label: "India (الهند)" },
  { code: "+966", label: "Saudi Arabia (السعودية)" },
  { code: "+974", label: "Qatar (قطر)" },
  { code: "+973", label: "Bahrain (البحرين)" },
  { code: "+965", label: "Kuwait (الكويت)" },
  { code: "+968", label: "Oman (عُمان)" },
  { code: "+20", label: "Egypt (مصر)" },
  { code: "+962", label: "Jordan (الأردن)" },
  { code: "+961", label: "Lebanon (لبنان)" },
  { code: "+212", label: "Morocco (المغرب)" },
  { code: "+213", label: "Algeria (الجزائر)" },
  { code: "+216", label: "Tunisia (تونس)" },
  { code: "+964", label: "Iraq (العراق)" },
  { code: "+970", label: "Palestine (فلسطين)" },
  { code: "+963", label: "Syria (سوريا)" },
  { code: "+967", label: "Yemen (اليمن)" },
  { code: "+218", label: "Libya (ليبيا)" },
  { code: "+249", label: "Sudan (السودان)" },
  { code: "+252", label: "Somalia (الصومال)" },
  { code: "+222", label: "Mauritania (موريتانيا)" },
  { code: "+253", label: "Djibouti (جيبوتي)" },
  { code: "+269", label: "Comoros (جزر القمر)" },
  { code: "+33", label: "France" },
  { code: "+49", label: "Germany" },
  { code: "+39", label: "Italy" },
  { code: "+34", label: "Spain" },
  { code: "+61", label: "Australia" },
  { code: "+86", label: "China" },
  { code: "+81", label: "Japan" },
  { code: "+82", label: "South Korea" },
  { code: "+55", label: "Brazil" },
  { code: "+52", label: "Mexico" },
  { code: "+54", label: "Argentina" },
  { code: "+7", label: "Russia/Kaz" },
  { code: "+27", label: "South Africa" },
  { code: "+234", label: "Nigeria" },
  { code: "+254", label: "Kenya" },
  { code: "+92", label: "Pakistan" },
  { code: "+880", label: "Bangladesh" },
  { code: "+62", label: "Indonesia" },
  { code: "+60", label: "Malaysia" },
  { code: "+63", label: "Philippines" },
  { code: "+65", label: "Singapore" },
  { code: "+66", label: "Thailand" },
  { code: "+84", label: "Vietnam" },
  { code: "+90", label: "Turkey" },
  { code: "+98", label: "Iran" },
  { code: "+93", label: "Afghanistan" },
  { code: "+43", label: "Austria" },
  { code: "+32", label: "Belgium" },
  { code: "+41", label: "Switzerland" },
  { code: "+46", label: "Sweden" },
  { code: "+47", label: "Norway" },
  { code: "+45", label: "Denmark" },
  { code: "+358", label: "Finland" },
  { code: "+31", label: "Netherlands" },
  { code: "+30", label: "Greece" },
  { code: "+351", label: "Portugal" },
  { code: "+48", label: "Poland" },
  { code: "+420", label: "Czechia" },
  { code: "+36", label: "Hungary" },
  { code: "+40", label: "Romania" },
  { code: "+353", label: "Ireland" },
  { code: "+64", label: "New Zealand" }
];
